### ISSUE TITLE
Add a link to the Textgraphs workshop - and your paper, etc

### ISSUE THREAD

**Issue by mdda** [aayushee/Textgraphs#1]
For example :
*  [The Textgraphs workshop](https://www.aclweb.org/anthology/volumes/2020.textgraphs-1/); and
*  [Our Paper](https://www.aclweb.org/anthology/2020.textgraphs-1.13/)

## Citation

If you found our work helpful in your research, consider citing the following:

> @inproceedings{gupta-srinivasaraghavan-2020-explanation,
>     title = "Explanation Regeneration via Multi-Hop {ILP} Inference over Knowledge Base",
>     author = "Gupta, Aayushee  and
>       Srinivasaraghavan, Gopalakrishnan",
>     booktitle = "Proceedings of the Graph-based Methods for Natural Language Processing (TextGraphs)",
>     month = dec,
>     year = "2020",
>     address = "Barcelona, Spain (Online)",
>     publisher = "Association for Computational Linguistics",
>     url = "https://www.aclweb.org/anthology/2020.textgraphs-1.13",
>     pages = "109--114",
>     abstract = "Textgraphs 2020 Workshop organized a shared task on {`}Explanation Regeneration{'} that required reconstructing gold explanations for elementary science questions. This work describes our submission to the task which is based on multiple components: a BERT baseline ranking, an Integer Linear Program (ILP) based re-scoring and a regression model for re-ranking the explanation facts. Our system achieved a Mean Average Precision score of 0.3659.",
> }
>

**Comment by aayushee** [comment]
Done. Thanks for the suggestion!
